### PR TITLE
Remove support for old PHP and fixes travis errors

### PR DESCRIPTION
**Pull request by sineverba**

### CODE REVIEW

**Comment by sineverba** [comment]
Just a ping... To know if you are interested in my contrib :)

**Comment by benjamin-smith** [comment]
Thanks for the contribution! Any specific reason you'd like to remove test support for older versions of PHP?

**Comment by sineverba** [comment]
I would remove old php support to implements new Phpunit (v7). Php7 on the other side offers so many improvements, instead of Php5.

**Comment by benjamin-smith** [comment]
I'd prefer not to drop support for older versions of PHP at this time. Thank you however!

**Pull request closed without merging**
